version: "3.3"

services:
  mywebsite-backend:
    hostname: localhost
    container_name: mywebsite-backend
    build: .
    ports:
      - 80:80
    environment:
      - funzt_database
      - funzt_jwtPrivateKey
      - funzt_mail_host
      - funzt_mail_port
      - funzt_mail_user
      - funzt_mail_password
