version: "3.3"

services:

  db:
    image: postgres
    container_name: mywebsite-db
    volumes:
      - ./db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD

  mywebsite-backend:
    hostname: localhost
    container_name: mywebsite-backend
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - database
      - jwtPrivateKey
      - mail_host
      - mail_port
      - mail_user
      - mail_password
